apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: argocd
data:
  avp.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      generate:
        command:
          - argocd-vault-plugin
          - generate
          - "."
      lockRepo: false
  avp-kustomize.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-kustomize
    spec:
      allowConcurrency: true
      generate:
        command:
          - sh
          - "-c"
          - "kustomize build . --enable-helm | argocd-vault-plugin generate -"
      lockRepo: false
  avp-helm.yaml: |
    ---
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin-helm
    spec:
      allowConcurrency: true
      init:
        command:
          - sh
          - "-c"
          - "helm dependency build"
      generate:
        command:
          - sh
          - "-c"
          - "helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE . --include-crds | argocd-vault-plugin generate -"
      lockRepo: false