all:
    children:
        proxmox:
            hosts:
                pve:
                    ansible_host: 10.30.0.50
                    ansible_user: root
        k8s_cluster:
            children:
                kube_control_plane:
                    hosts:
                        k8s-master:
                            ansible_host: 10.30.0.200
                            etcd_member_name: master
                kube_node:
                    hosts:
                        k8s-worker-01:
                            ansible_host: 10.30.0.201
                        k8s-worker-02:
                            ansible_host: 10.30.0.202
                        k8s-worker-03:
                            ansible_host: 10.30.0.203
                etcd:
                    children:
                        kube_control_plane: null
            vars:
                ssh_pubkey: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC4W3rAh7Ygy7ljq2aTL5pRtNSDNtHBjuPgDk6ub7AMC navanin
