apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backupers
  namespace: argocd
spec:
  destination:
    namespace: backupers
    server: https://kubernetes.default.svc
  project: homelab
  source:
    path:  kubernetes/backupers
    repoURL: https://github.com/navanin/homelab.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
