apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: homelab
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 0.31.0
    helm:
      releaseName: longhorn
      # values: |
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn